export const STRINGS = {
  LOGIN: {
    CHALLENGE_TITLE: 'LEMON CHALLENGE',
    TITLE: 'Sign in with:',
    GOOGLE: {
      ERROR_NO_USER_INFO: 'Could not retrieve user information',
      ERROR_CANCELLED: 'Sign-in was cancelled',
      ERROR_IN_PROGRESS: 'Sign-in is already in progress',
      ERROR_PLAY_SERVICES: 'Google Play Services is not available',
      ERROR_UNEXPECTED: 'An unexpected error occurred. Please try again.',
    },
  },
  HOME: {
    TAB_LABEL: 'Home',
    TITLE: 'Home Screen',
    SEARCH: 'Search (Tether, Bitcoin...)',
    VARIATION_ACTION: {
      ALL: 'Var: All',
      POSITIVE: 'Var: +',
      NEGATIVE: 'Var: -',
    },
    SORT_ASC_ACTION: 'Asc',
    SORT_DESC_ACTION: 'Desc',
    MIN_PRICE: 'Min $',
    MAX_PRICE: 'Max $',
    LOADING: 'Loading...',
    EMPTY: 'No data available',
  },
  EXCHANGE: {
    TAB_LABEL: 'Exchange',
    TITLE: 'Cryptocurrency Exchange',
    FROM: 'From',
    TO: 'To',
    SELECT_CRYPTO: 'Select Cryptocurrency',
    SELECT_FIAT: 'Select Fiat Currency',
    AMOUNT: 'Amount',
    PICKER_TITLE_CRYPTO: 'Select Cryptocurrency',
    PICKER_TITLE_FIAT: 'Select Fiat Currency',
    SEARCH_PLACEHOLDER: 'Search for a currency...',
  },
  PROFILE: {
    TITLE: 'Profile',
    TAB_LABEL: 'Profile',
    LOGOUT_ACTION: 'Log out',
    EMAIL: 'Email:',
  },
  GENERIC: {
    RETRY: 'Retry',
  },
};
